package way.application.core.utils;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

import org.springframework.http.HttpStatus;

@Getter
@RequiredArgsConstructor
public enum ErrorResult {

	// TODO: EXCEPTION CODE 값 및 MESSAGE 변경 필요
	// BAD_REQUEST
	MEMBER_SEQ_BAD_REQUEST_EXCEPTION(HttpStatus.BAD_REQUEST, "MEMBER_SEQ_BAD_REQUEST_EXCEPTION", "MSB002"),
	SCHEDULE_SEQ_BAD_REQUEST_EXCEPTION(HttpStatus.BAD_REQUEST, "SCHEDULE_SEQ_BAD_REQUEST_EXCEPTION", "SSB003"),
	MEMBER_SEQ_NOT_IN_SCHEDULE_BAD_REQUEST_EXCEPTION(HttpStatus.BAD_REQUEST,
		"MEMBER_SEQ_NOT_IN_SCHEDULE_BAD_REQUEST_EXCEPTION", "MSNISB004"),
	LOCATION_OVER_TEN_BAD_REQUEST_EXCEPTION(HttpStatus.BAD_REQUEST, "SAVED_LOCATION_OVER_TEN_BAD_EXCEPTION",
		"SLOTB005"),
	LOCATION_SEQ_BAD_REQUEST_EXCEPTION(HttpStatus.BAD_REQUEST, "LOCATION_SEQ_BAD_REQUEST_EXCEPTION", "LSB006"),
	LOCATION_DIDNT_CREATED_BY_MEMBER_BAD_REQUEST_EXCEPTION(HttpStatus.BAD_REQUEST,
		"LOCATION_DIDNT_CREATED_BY_MEMBER_BAD_REQUEST_EXCEPTION", "LDCBMB007"),
	SCHEDULE_DIDNT_CREATED_BY_MEMBER_BAD_REQUEST_EXCEPTION(HttpStatus.BAD_REQUEST,
		"SCHEDULE_DIDNT_CREATED_BY_MEMBER_BAD_REQUEST_EXCEPTION", "SDCBMB008"),
	PASSWORD_BAD_REQUEST_EXCEPTION(HttpStatus.BAD_REQUEST, "PASSWORD_BAD_REQUEST_EXCEPTION", "PB005"),
	EMAIL_BAD_REQUEST_EXCEPTION(HttpStatus.BAD_REQUEST, "EMAIL_BAR_REQUEST_EXCEPTION", "EB009"),
	USER_ID_BAD_REQUEST_EXCEPTION(HttpStatus.BAD_REQUEST, "USER_ID_BAD_REQUEST_EXCEPTION", "UIB010"),
	CODE_BAD_REQUEST_EXCEPTION(HttpStatus.BAD_REQUEST, "CODE_BAD_REQUEST_EXCEPTION", "CB011"),
	USER_MISMATCH_BAD_REQUEST_EXCEPTION(HttpStatus.BAD_REQUEST, "USER_MISMATCH_BAD_REQUEST_EXCEPTION", "UMB012"),
	PASSWORD_MISMATCH_BAD_REQUEST_EXCEPTION(HttpStatus.BAD_REQUEST, "PASSWORD_MISMATCH_BAD_REQUEST_EXCEPTION",
		"PMB013"),
	SELF_SEARCH_BAD_REQUEST_EXCEPTION(HttpStatus.BAD_REQUEST, "SELF_SEARCH_BAD_REQUEST_EXCEPTION", "SSB014"),
	SELF_FRIEND_REQUEST_BAD_REQUEST_EXCEPTION(HttpStatus.BAD_REQUEST, "SELF_FRIEND_REQUEST_BAD_REQUEST_EXCEPTION", "SFRB015"),
	ALREADY_FRIEND_BAD_REQUEST_EXCEPTION(HttpStatus.BAD_REQUEST, "ALREADY_FRIEND_BAD_REQUEST_EXCEPTION", "AFB016"),
	ALREADY_SENT_BAD_REQUEST_EXCEPTION(HttpStatus.BAD_REQUEST,"ALREADY_SENT_BAD_REQUEST_EXCEPTION","ASB017"),
	ALREADY_SENT_BY_FRIEND_BAD_REQUEST_EXCEPTION(HttpStatus.BAD_REQUEST,"ALREADY_SENT_BY_FRIEND_BAD_REQUEST_EXCEPTION","ASBFB018"),


	// SERVER
	FIREBASE_CLOUD_MESSAGING_EXCEPTION(HttpStatus.INTERNAL_SERVER_ERROR, "FIREBASE_CLOUD_MESSAGING_EXCEPTION", "S501"),
	UNKNOWN_EXCEPTION(HttpStatus.INTERNAL_SERVER_ERROR, "Unknown Exception", "S500"),

	//conflict
	USER_ID_DUPLICATION_EXCEPTION(HttpStatus.CONFLICT, "USER_ID_DUPLICATION_CONFLICT_EXCEPTION", "UIDC001"),
	EMAIL_DUPLICATION_EXCEPTION(HttpStatus.CONFLICT, "EMAIL_DUPLICATION_CONFLICT_EXCEPTION", "EDC002");

	private final HttpStatus httpStatus;
	private final String message;
	private final String code;
}
